services:
  jpeg-server:
    image: looprcontainerregistry.azurecr.io/jpeg-server:v1
    ports:
      - "5000:5000"
    environment:
      - VIDEO_PATH=/app/data/2024-03-12/output.mp4
    volumes:
      - /home/om-surushe/Documents/cascade-testing/data:/app/data